### ISSUE TITLE
🌐 Community Hub for Gradle plugins and integrations

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/community#15]
I am interested in building a community hub and community-governed GitHub organization that would offer a home for plugins and other vital component, whose maintainers who want to ensure continuity of the plugins. I call it _Project Gradliverse_ (inspired by Quarkus's [Quarkiverse](https://github.com/quarkiverse)), but this is not a finalized name.

From the implementation standpoint, It would be a standalone open-source GitHub organization that:

1. Hosts repositories and offers various automation to simplify the life of maintainers: CI/CD, integration testing, release flow, changelogs, documentation hosting
2. Encourages the best practices for plugin development, ideally by offering a kind of plugin health score and recommendations/certifications for the plugins following the best practices
3. Modeled in a confederation way. All repositories can join, with a low bar for doing so. Also, maintainers can leave the organization or archive the projects if there is a consensus to do so
4. Has an open and transparent governance model that offers the maintainers almost full powers but defines a transition process should the maintainer want to move one or become inactive. It is somehow aligned with how [Jenkins governance](https://www.jenkins.io/project/governance) is defined and how we support maintainers
5. Integrates with existing ecosystem as much as possible: the Gradle website, community documentation, etc., etc.
6. Remains vendor-agnostic and open to collaboration, including adding maintainers from any organization. The governance model is focused on individuals

## Potential Pilot projects

- Shadow Plugin for Gradle - https://github.com/johnrengelman/shadow/issues/908
- Projects from Gradle core should there be a consensus to detach them
- // Suggestions are welcome!

## Discuss

- `#roadmap` channel on the community Slack

## References

- [Quarkiverse](https://github.com/quarkiverse) - similar hub for Quarkus
- Jenkins - the main `jenkinsci` organization is built in the same way
- [Gradle X](https://gradlex.org/) - A collection of high quality Gradle plugins - some recommendations and best practices can be used from there, and maybe _Gradliverse_ idea could be merged into this project
- [GradleUp](https://github.com/GradleUp) - Also a collection of Gradle plugins

## Scope

```[tasklist]
### Tasks
- [x] Initial Proposal, based on feedback
- [ ] Legal and IT approvals
- [ ] Initial setup for a few pilot projects
- [ ] Hosting and community governance guidelines
- [ ] Release Automation and templates
- [ ] Public Announcement
```

**Comment by 3flex** [comment]
Another pilot candidate: https://github.com/ben-manes/gradle-versions-plugin

I won't tag him here but I recall Ben saying previously that this should have better support from Gradle directly. This seems like a good middle ground.

**Comment by oleg-nenashev** [comment]
@lacasseio sorry, I dropped the ball on responding.I actually had it in the drafts :( 

The Gradle Plugin Portal is **definitely** a part of the longer-term vision for this initiative. As you sais, many features can and should be implemented there. In particular, we had a discussion with @ljacomet and a few stakeholders about updating the plugin portal UI or... maybe even replacing the user-facing bits by a generic open source plugin marketplace engine. There is even a pending idea about reusing bits of https://plugins.jenkins.io/ and a few other portals in a new open-source project for that. For backend tooling and hosting, the current portal implementation is here to stay.

To address your comments about enforcement,  there is no goal to enforce anything or to force migration to the new organization by providing org-only features or preferential threatment. The Community Hub does not even have to be owned by Gradle IMO. It could be another entity, e,g, CommonHaus established recently.


Below, there are comments on a few points:

> I'm generally not a massive fan of point number 1 because it hides the underlying problem with project automation, which is the lack of "composable automation" for projects.... Despite the initial idea, the practicality of this goal is quite poor as there are so many possible tools/CI/etc. to integrate with. Forcing developers to use particular technologies is where most projects go to die.

Nothing is going to be forced. But yes, I consider offering reusable automation on GitHub Actions for those maintainers who want to adopt it. All auutomation will be supplied via reusable components that could be used within the suggested GitHub organization or not: GitHub Action Steps, Gradle Convention Plugin, etc. But it is totally up to plugin maintainers to adopt them or not

> That solution is better and more applicable to the entire ecosystem than gatekeeping the health score to only plugins on the central hub.

It will not be gatekeeped to a single GitHub organization. As long as metrics can be collected from the plugin portal (ofc needs API) or from repository (e.g. GitHub API), there is no dependency on a single organization. In Jenkins and in R.I.P. LibreCores, metrics were collected in a more or less agnostic way.

> All repositories can join, with a low bar for doing so.
>> This point describes how the plugin portal works at the moment. 

Plugin Portal does not manage source code repositories. For the rest, indeed some transfer features will need to be implemented there

> For example, projects that agree to the governance have to invite a special GitHub user that Gradle maintains to hand off the repository to another maintainer. 

There is no way to ensure sustainability of this solution in GitHub organization (e.g. admin might be removed). And for individual account where many plugins live now, there is just no way to do that. Organization transfer makes it easier.

> Integrates with existing ecosystem as much as possible: the Gradle website, community documentation, etc., etc.
>> This point still describes the plugin portal.

Yes, and it **is** the Plugin portal which is definitely in the scope in longer run
E.g. https://plugins.jenkins.io/gradle/ for example

> Remains vendor-agnostic and open to collaboration, including adding maintainers from any organization. The governance model is focused on individuals.
>> The current state of the community plugins is already vendor-agnostic, letting all maintainers use whatever they want.

Yes, and hence **remains** despite the introduction of a new entity that does some consolidation

> Within the Gradle codebase, plugin development works great (been there). But as soon as we step out, there is a huge lack of support. Centralizing plugins takes the easy way around the core issue. We should spend more time solving that issue instead of working around it.

I totally support that. And it is on my radars too

**Comment by JamesXNelson** [comment]
I love the idea of this, but I kinda hate the name `gradliverse`.  Really, the `i` seems out of place. Do I pronounce this "gradle-ee-verse" or "gradle-i-verse"?  The extra phoneme in the middle for both feels ...clumsy.

Alternatives name suggestions in increasing order of personal preference:
`gradlverse`
`gradleverse` 
`gradlehub`

**Comment by JamesXNelson** [comment]
also, as a completely random third party interjecting where I have no authority whatsoever... I think oleg's idea is important outside of the lens of "core gradle-maintained ecosystem / plugin portal"....  for plugins that have many users but a burned out maintainer, the only future for that plugin is a fork, often done at the whim of some random helpful person (who hopefully isn't going to hijack a popular plugin and then insert vulnerabilities into it).

It doesn't matter if improving the official plugin portal would make things _functionally_ better, the issue I believe is that a community-managed org/hub would be able to absorb the abandoned-but-popular plugins with some oversight and community involvement / official process to move from individual-maintained to org-maintained, without requiring every abandoned plugin to create its own org / standards / tooling / etc. 

A plugin with a group id like `com.gradlecommunity` or `com.gradlehub` would confer a slight bump in credibility over `com.mynamehere`, and I think that credibility would be well-deserved, since a project maintained by a community org actually does have more oversight than "random person on github has a popular plugin they do whatever they want with".

...so.... I don't think this is something that _can_ be fixed on gradle's end / with better plugin portal features. It doesn't matter how well the plugin portal works if the person maintaining the code decides to spend time with their kids instead of maintaining a popular hobby project. Even if you can transfer ownership of plugins on gradle's side, it still requires a new maintainer in github, and having that new maintainer be an org with some standards / rules / official processes is always going to be better than "well, `@coolDude743` has a fork that seems active, guess I'll run their code on my intranet".

**Comment by oleg-nenashev** [comment]
> I love the idea of this, but I kinda hate the name gradliverse.... The extra phoneme in the middle for both feels ...clumsy.

This name is not finalized, and feedback is more than welcome :)
FWIW my mother tongue is Russian, and there "i" or another vowel separator would be rather expected in such a name

> A plugin with a group id like com.gradlecommunity or com.gradlehub would confer a slight bump in credibility over com.mynamehere

It is right. At the same time Gradle has no notion of changing Group IDs like Apache Maven has with Relocation JARs, or like other plugin ecosystems handle on their own (e.g. Jenkins plugins that operate solely based on ID). So changing the groupID will be a breaking change as of now, but I agree that for some cases it will be necessary.
